server.port=9020

#spring.datasource.url=jdbc:mariadb://mariadb-container-feedback:3306/cluster
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mariadb://mariadb-container-feedback:3306/cluster
spring.datasource.username=userCRUD
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#CREATE USER 'userCRUD'@'localhost' IDENTIFIED BY 'password';
#CREATE USER 'adminCRUD'@'localhost' IDENTIFIED BY 'password';

#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.user TO 'userCRUD'@'localhost';
#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.code_message TO 'userCRUD'@'localhost';
#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.code_record TO 'userCRUD'@'localhost';

#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.ip_public_address TO 'adminCRUD'@'localhost';
#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.log_messages_execution_node TO 'userCRUD'@'localhost';
#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.log_messages_http_node TO 'userCRUD'@'localhost';
#GRANT SELECT, INSERT, UPDATE, DELETE ON cluster.log_messages_master_node TO 'userCRUD'@'localhost';

#FLUSH PRIVILEGES;

internPassword=GrtIw3=Gl+iSE!nlc2KYu=Aksaau!97hw1nHh#X!=4Ilsk%Y*Kg8Gax$#1T$953fvfG--jdv9Z4RR*D7i+HDRoc#-oujScS0UoId^A5kQE2fmv74xBl&Oka-E6cY_R7#MA_P*nk+4m_wPsT@xdo@9B%sWq8i8JEpC52NVlk7jhhGX3zik3zylJMF67e4Vv_C1uWR%9wz



