server.port=9030

#spring.datasource.url=jdbc:mariadb://mariadb-container-ip:3306/cluster
#spring.datasource.url=jdbc:mariadb://mariadb-container:3306/cluster
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mariadb://mariadb-container-ip:3306/cluster
spring.datasource.username=adminCRUD
spring.datasource.password=password2
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

internPassword=GrtIw3=Gl+iSE!nlc2KYu=Aksaau!97hw1nHh#X!=4Ilsk%Y*Kg8Gax$#1T$953fvfG--jdv9Z4RR*D7i+HDRoc#-oujScS0UoId^A5kQE2fmv74xBl&Oka-E6cY_R7#MA_P*nk+4m_wPsT@xdo@9B%sWq8i8JEpC52NVlk7jhhGX3zik3zylJMF67e4Vv_C1uWR%9wz



