server.port=8070
server.address=0.0.0.0

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=mongodb-container
spring.data.mongodb.port=27017
spring.data.mongodb.username=root
spring.data.mongodb.password=password
spring.data.mongodb.database=cluster

internPassword=GrtIw3=Gl+iSE!nlc2KYu=Aksaau!97hw1nHh#X!=4Ilsk%Y*Kg8Gax$#1T$953fvfG--jdv9Z4RR*D7i+HDRoc#-oujScS0UoId^A5kQE2fmv74xBl&Oka-E6cY_R7#MA_P*nk+4m_wPsT@xdo@9B%sWq8i8JEpC52NVlk7jhhGX3zik3zylJMF67e4Vv_C1uWR%9wz
